add porter art
getporter/community pull request #3
Opened 2020-09-21 21:29 UTC by flynnduism

Adds an art section to this repo with all of the branding stuff, logos, styleguide, cat usage guidelines etc.

2020-09-22 16:00 UTC, carolynvs requested changes
I LOVE IT! ❤️

The tiny icon, that we will use for 32px and smaller for the favicon is the only one that needs some slight changes so that it looks like the logo still when that small.

2020-09-22 20:33 UTC, flynnduism commented
Updated with a new variant for the small icon:

![apple-touch-icon](https://user-images.githubusercontent.com/686194/93934554-2dd09000-fcd8-11ea-8ac3-59be9fe0aa54.png)

2020-09-22 20:38 UTC, carolynvs requested changes
nit: Can you update the pictures to use the new cute icon?

2020-09-24 14:31 UTC, carolynvs requested changes

2020-09-24 14:31 UTC, carolynvs commented on art/icon/porter-icon-small.svg
> +    <g id="icon-small" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
This svg looks different than the porter-icon-small.png making the face transparent instead of orange.

2020-09-24 14:31 UTC, carolynvs commented on art/README.md
> +<img width="1069" alt="overview" src="https://user-images.githubusercontent.com/686194/93821987-5727e800-fc14-11ea-8bed-8034fa8eda75.png">
This image still has the old small icons in it.

2020-09-25 20:19 UTC, carolynvs approved these changes
Thank you! 🙇‍♀️

2020-09-25 20:19 UTC, merged